/** Canonical Freedom Paws brand image paths (generated by npm run brand:assets). */

export const BRAND_LOGO_MASTER = '/images/brand/logo-master-stacked.png';
export const BRAND_LOGO_PAW = '/images/brand/logo-paw.png';
export const BRAND_LOGO_HERO = '/images/brand/logo-hero.png';
