/**
 * Top-20 severe canine conditions & visual/text indicators for ViT urgent gating.
 * Only conditions in this database can trigger vetUrgent — mild/moderate signs route to protocols.
 */

export type SevereConditionRecord = {
  id: string;
  name: string;
  category: 'mass' | 'hepatic' | 'cardiac' | 'respiratory' | 'trauma' | 'neuro' | 'gi' | 'urinary' | 'toxic' | 'other';
  /** Owner-reported symptom phrases (normalized substring match). */
  indicators: string[];
  /** Phrases expected in AI visualFindings. */
  visualIndicators: string[];
  /** Weight 1–3 — higher = stronger signal when matched. */
  indicatorWeights?: Partial<Record<string, 1 | 2 | 3>>;
};

/** Congruency required before raising vetUrgent (0–100). */
export const URGENT_CONGRUENCY_THRESHOLD = 80;

/**
 * Mild/moderate patterns — if ONLY these match (no severe ≥ threshold), never flag urgent.
 * Supports wellness-first routing to lifestyle, detox, and supplementation.
 */
export const MILD_MODERATE_EXCLUSIONS: string[] = [
  'mild limp',
  'slight limp',
  'occasional limp',
  'intermittent limp',
  'mild cough',
  'occasional cough',
  'dry cough',
  'mild itch',
  'mild itching',
  'seasonal allergies',
  'mild allergy',
  'scratching sometimes',
  'mild rash',
  'small hot spot',
  'mild digestive',
  'soft stool',
  'loose stool occasional',
  'mild gas',
  'mild bloating',
  'senior stiffness',
  'mild stiffness',
  'slowing down',
  'mild cloudiness',
  'slight discharge',
  'mild tartar',
  'bad breath mild',
  'mild anxiety',
  'mild lethargy',
  'tired today',
  'low energy mild',
  'small lump stable',
  'old lump unchanged',
  'lipoma',
  'fatty lump',
  'skin tag',
  'wart',
  'callus',
  'mild ear infection',
  'dirty ears',
  'mild redness',
  'dandruff',
  'dry skin mild',
  'shedding',
  'weight gain mild',
  'slightly overweight',
];

export const SEVERE_CONDITIONS: SevereConditionRecord[] = [
  {
    id: 'malignant_mass',
    name: 'Suspicious or fast-growing mass / tumor',
    category: 'mass',
    indicators: [
      'fast growing lump',
      'rapidly growing mass',
      'tumor',
      'malignant',
      'cancer',
      'hard lump',
      'irregular mass',
      'ulcerated mass',
      'bleeding lump',
      'open sore on lump',
      'mass doubling',
      'new large lump',
    ],
    visualIndicators: [
      'irregular mass',
      'ulcerated lump',
      'fast growing mass',
      'large tumor',
      'bleeding mass',
      'asymmetric swelling',
      'open wound on mass',
    ],
  },
  {
    id: 'jaundice',
    name: 'Jaundice (icterus)',
    category: 'hepatic',
    indicators: [
      'jaundice',
      'yellow gums',
      'yellow eyes',
      'yellow skin',
      'icterus',
      'yellow whites of eyes',
      'yellow tint',
      'liver failure',
      'yellow mucous membranes',
    ],
    visualIndicators: [
      'yellow gums',
      'yellow sclera',
      'icteric',
      'jaundiced',
      'yellow mucous membranes',
      'yellow skin tint',
    ],
  },
  {
    id: 'collapse_syncope',
    name: 'Collapse or syncope',
    category: 'cardiac',
    indicators: [
      'collapsed',
      'collapse',
      'fainted',
      'syncope',
      'passed out',
      'unconscious',
      'cant stand up',
      'cannot stand',
      'went down suddenly',
      'fell over',
    ],
    visualIndicators: ['collapsed', 'lying unresponsive', 'unable to rise', 'acute collapse'],
  },
  {
    id: 'severe_respiratory_distress',
    name: 'Severe respiratory distress',
    category: 'respiratory',
    indicators: [
      'cant breathe',
      'cannot breathe',
      'gasping',
      'severe breathing difficulty',
      'respiratory distress',
      'choking',
      'blue tongue',
      'open mouth breathing at rest',
      'gasping for air',
    ],
    visualIndicators: [
      'labored breathing',
      'open mouth breathing',
      'gasping',
      'severe respiratory distress',
      'cyanosis',
      'blue gums',
    ],
  },
  {
    id: 'cyanosis_pale_gums',
    name: 'Cyanosis or critically pale gums',
    category: 'cardiac',
    indicators: [
      'blue gums',
      'pale gums',
      'white gums',
      'gray gums',
      'cyanosis',
      'gums very pale',
      'brick red then pale',
    ],
    visualIndicators: ['pale gums', 'blue gums', 'white gums', 'cyanotic', 'gray mucous membranes'],
  },
  {
    id: 'uncontrolled_bleeding',
    name: 'Uncontrolled bleeding / hemorrhage',
    category: 'trauma',
    indicators: [
      'bleeding wont stop',
      'profuse bleeding',
      'heavy bleeding',
      'hemorrhage',
      'blood loss',
      'bleeding heavily',
      'spurting blood',
    ],
    visualIndicators: ['active bleeding', 'profuse bleeding', 'blood pooling', 'open arterial bleed'],
  },
  {
    id: 'acute_trauma',
    name: 'Acute severe trauma',
    category: 'trauma',
    indicators: [
      'hit by car',
      'car accident',
      'fall from height',
      'dog fight severe',
      'bite wound deep',
      'broken bone visible',
      'open fracture',
      'severe injury',
    ],
    visualIndicators: ['open fracture', 'deep laceration', 'severe trauma', 'crush injury', 'penetrating wound'],
  },
  {
    id: 'gastric_dilatation_bloat',
    name: 'Gastric dilatation-volvulus (bloat)',
    category: 'gi',
    indicators: [
      'bloat',
      'gdv',
      'distended abdomen painful',
      'hard swollen belly',
      'trying to vomit nothing',
      'unproductive retching',
      'bloated stomach emergency',
    ],
    visualIndicators: [
      'distended tense abdomen',
      'bloated abdomen',
      'unproductive retching posture',
      'prayer position',
    ],
  },
  {
    id: 'seizures',
    name: 'Seizures / status epilepticus',
    category: 'neuro',
    indicators: [
      'seizure',
      'seizing',
      'convulsion',
      'status epilepticus',
      'multiple seizures',
      'seiz',
      'fits repeatedly',
      'shaking uncontrollably seizure',
    ],
    visualIndicators: ['active seizure', 'convulsing', 'tonic clonic activity', 'post ictal'],
  },
  {
    id: 'urinary_obstruction',
    name: 'Urinary obstruction / unable to urinate',
    category: 'urinary',
    indicators: [
      'cant pee',
      'cannot urinate',
      'straining no urine',
      'blocked bladder',
      'urinary obstruction',
      'no urine output',
      'painful urination none',
    ],
    visualIndicators: ['straining to urinate', 'distended bladder', 'no urine production'],
  },
  {
    id: 'shock_dehydration',
    name: 'Shock or severe dehydration',
    category: 'other',
    indicators: [
      'shock',
      'severe dehydration',
      'skin tenting severe',
      'cold extremities',
      'weak pulse',
      'gums sticky dry',
      'not drinking days',
    ],
    visualIndicators: ['prolonged skin tent', 'weak collapse', 'shock signs', 'severely sunken eyes'],
  },
  {
    id: 'eye_proptosis',
    name: 'Eye proptosis / ruptured globe',
    category: 'trauma',
    indicators: [
      'eye popped out',
      'proptosis',
      'eye bulging out',
      'ruptured eye',
      'eye injury severe',
    ],
    visualIndicators: ['proptosed eye', 'globe rupture', 'eye out of socket', 'severe ocular trauma'],
  },
  {
    id: 'heatstroke',
    name: 'Heatstroke / hyperthermia',
    category: 'other',
    indicators: [
      'heatstroke',
      'heat stroke',
      'overheated',
      'high fever dog',
      'panting collapse hot',
      'left in hot car',
    ],
    visualIndicators: ['hyperthermia', 'excessive panting collapse', 'bright red gums heat', 'hot to touch distress'],
  },
  {
    id: 'poisoning_toxin',
    name: 'Suspected poisoning / toxin exposure',
    category: 'toxic',
    indicators: [
      'poisoned',
      'poisoning',
      'ate chocolate',
      'rat poison',
      'antifreeze',
      'toxin ingestion',
      'grape ingestion',
      'xylitol',
      'unknown toxin',
    ],
    visualIndicators: ['toxin exposure reported', 'vomiting after toxin', 'acute neuro signs toxin'],
  },
  {
    id: 'paralysis',
    name: 'Acute paralysis / inability to move limbs',
    category: 'neuro',
    indicators: [
      'paralyzed',
      'paralysis',
      'cant move legs',
      'cannot walk suddenly',
      'dragging back legs acute',
      'sudden hind limb paralysis',
      'ivdd acute',
    ],
    visualIndicators: ['acute paralysis', 'dragging limbs', 'unable to walk suddenly', 'non ambulatory'],
  },
  {
    id: 'severe_anemia',
    name: 'Severe anemia / critical pallor',
    category: 'other',
    indicators: [
      'severe anemia',
      'very pale gums',
      'white gums anemia',
      'bleeding internally',
      'bloody diarrhea severe',
    ],
    visualIndicators: ['extreme pallor', 'white mucous membranes', 'severe anemia signs'],
  },
  {
    id: 'hematemesis_melena',
    name: 'Vomiting blood / melena',
    category: 'gi',
    indicators: [
      'vomiting blood',
      'blood in vomit',
      'hematemesis',
      'black tarry stool',
      'melena',
      'bloody vomit',
    ],
    visualIndicators: ['blood in vomit', 'hematemesis', 'melena', 'coffee ground vomit'],
  },
  {
    id: 'foreign_body_obstruction',
    name: 'Severe foreign body / GI obstruction',
    category: 'gi',
    indicators: [
      'swallowed object blocking',
      'foreign body obstruction',
      'cant keep water down',
      'repeated vomiting bile',
      'string swallowed',
      'blocked intestine',
    ],
    visualIndicators: ['repeated vomiting', 'painful abdomen vomiting', 'obstruction signs'],
  },
  {
    id: 'difficulty_breathing_rest',
    name: 'Difficulty breathing at rest',
    category: 'respiratory',
    indicators: [
      'breathing hard at rest',
      'resting respiratory distress',
      'fast breathing at rest',
      'tachypnea at rest',
      'labored breathing resting',
    ],
    visualIndicators: ['increased respiratory effort at rest', 'abdominal breathing at rest', 'nostril flare at rest'],
  },
  {
    id: 'acute_abdominal_pain',
    name: 'Acute severe abdominal pain',
    category: 'gi',
    indicators: [
      'severe abdominal pain',
      'screaming in pain belly',
      'hunched painful abdomen',
      'abdomen very painful',
      'guarding abdomen',
    ],
    visualIndicators: ['prayer position pain', 'hunched abdomen', 'guarding belly', 'severe pain posture'],
  },
];

export const SEVERE_CONDITION_IDS = SEVERE_CONDITIONS.map((c) => c.id);

export function getSevereConditionById(id: string): SevereConditionRecord | undefined {
  return SEVERE_CONDITIONS.find((c) => c.id === id);
}
