/**
 * Domain symptom lexicon: owner language → canonical terms → Freedom Paws protocols.
 * Expand aliases from real user input and VeNom presenting-complaint terms over time.
 */

import { SPEC_CATEGORY_SYMPTOM_EXPANSIONS } from './symptom-lexicon-spec-expansions';
import type { SymptomEntry } from './symptom-entry';

export type { SymptomEntry } from './symptom-entry';

/** Short label shown in ViT results (part before en-dash in protocol title). */
export function protocolDisplayName(fullTitle: string): string {
  const dash = fullTitle.indexOf(' – ');
  return dash >= 0 ? fullTitle.slice(0, dash) : fullTitle;
}

export const SYMPTOM_LEXICON: SymptomEntry[] = [
  // ── Eyes (highest clinical priority) ──────────────────────────────────────
  {
    id: 'eye_cloudy',
    canonical: 'cloudy / hazy eyes',
    aliases: [
      'cloudy eye',
      'cloudy eyes',
      'hazy eye',
      'blue haze',
      'white eye',
      'cataract',
      'cataracts',
      'milky eye',
      'opaque eye',
    ],
    protocol: 'Clear Vision Defender – Eye Health Protocol',
    priority: 10,
  },
  {
    id: 'eye_discharge',
    canonical: 'eye discharge / irritation',
    aliases: [
      'eye discharge',
      'goopy eye',
      'gunky eye',
      'eye booger',
      'eye boogers',
      'red eye',
      'red eyes',
      'squinting',
      'squint',
      'pawing at eye',
      'pawing eyes',
      'rubbing eye',
      'tearing',
      'watery eye',
      'watery eyes',
      'runny eye',
    ],
    protocol: 'Clear Vision Defender – Eye Health Protocol',
    priority: 11,
  },
  {
    id: 'eye_vision',
    canonical: 'vision loss',
    aliases: [
      'vision',
      'blind',
      'blindness',
      'cant see',
      "can't see",
      'bumping into things',
      'vision loss',
      'poor vision',
    ],
    protocol: 'Clear Vision Defender – Eye Health Protocol',
    priority: 12,
  },

  // ── Dental ────────────────────────────────────────────────────────────────
  {
    id: 'dental_oral',
    canonical: 'dental / oral issues',
    aliases: [
      'bad breath',
      'halitosis',
      'stinky breath',
      'drooling',
      'excessive drool',
      'red gums',
      'swollen gums',
      'bleeding gums',
      'tartar',
      'plaque',
      'yellow teeth',
      'brown teeth',
      'tooth pain',
      'broken tooth',
      'loose tooth',
      'dental',
      'oral health',
      'mouth pain',
      'not eating hard food',
    ],
    protocol: 'Fresh Smile Dental & Oral Health',
    priority: 20,
  },

  // ── Skin / allergy ────────────────────────────────────────────────────────
  {
    id: 'skin_pruritus',
    canonical: 'itching / scratching',
    aliases: [
      'itch',
      'itchy',
      'itching',
      'scratch',
      'scratching',
      'scratches',
      'chewing paws',
      'licking paws',
      'licking feet',
      'chewing feet',
      'biting skin',
      'cant stop scratching',
      "can't stop scratching",
    ],
    protocol: 'Allergy Shield – Skin & Coat Glow',
    priority: 30,
  },
  {
    id: 'skin_rash',
    canonical: 'rash / skin irritation',
    aliases: [
      'rash',
      'rashes',
      'hives',
      'hot spot',
      'hot spots',
      'red skin',
      'irritated skin',
      'skin irritation',
      'dermatitis',
      'eczema',
      'allergy',
      'allergies',
      'allergic',
      'sensitive skin',
    ],
    protocol: 'Allergy Shield – Skin & Coat Glow',
    priority: 31,
  },
  {
    id: 'skin_coat',
    canonical: 'coat / hair problems',
    aliases: [
      'hair loss',
      'balding',
      'bald patch',
      'bald spots',
      'alopecia',
      'flaky skin',
      'dry skin',
      'dull coat',
      'poor coat',
      'skin',
      'coat',
      'shedding excessively',
    ],
    protocol: 'Allergy Shield – Skin & Coat Glow',
    priority: 32,
  },

  // ── Digestive ─────────────────────────────────────────────────────────────
  {
    id: 'gut_diarrhea',
    canonical: 'diarrhea / loose stool',
    aliases: [
      'diarrhea',
      'diarrhoea',
      'loose stool',
      'loose poop',
      'runny poop',
      'runny stool',
      'watery stool',
      'soft stool',
      'accidents in house',
      'pooping inside',
    ],
    protocol: "Buddy's Gut Balance & Cleanse",
    priority: 40,
  },
  {
    id: 'gut_constipation',
    canonical: 'constipation',
    aliases: [
      'constipation',
      'constipated',
      'cant poop',
      "can't poop",
      'cannot poop',
      'straining to poop',
      'straining',
      'hard stool',
      'hard poop',
      'blocked up',
      'not pooping',
      'no bowel movement',
    ],
    protocol: "Buddy's Gut Balance & Cleanse",
    priority: 41,
  },
  {
    id: 'gut_nausea',
    canonical: 'vomiting / nausea',
    aliases: [
      'vomit',
      'vomiting',
      'throwing up',
      'threw up',
      'nausea',
      'nauseous',
      'gagging',
      'regurgitating',
      'upchuck',
      'sick stomach',
    ],
    protocol: "Buddy's Gut Balance & Cleanse",
    priority: 42,
  },
  {
    id: 'gut_general',
    canonical: 'digestive upset',
    aliases: [
      'gut',
      'stomach',
      'stomach upset',
      'digestive',
      'digestion',
      'bloat',
      'bloated',
      'gassy',
      'gas',
      'poop',
      'pooping',
      'stool',
      'bowel',
      'ibd',
      'upset tummy',
      'tummy trouble',
    ],
    protocol: "Buddy's Gut Balance & Cleanse",
    priority: 43,
  },

  // ── Joints / movement ─────────────────────────────────────────────────────
  {
    id: 'joint_lameness',
    canonical: 'lameness / limping',
    aliases: [
      'limp',
      'limping',
      'lameness',
      'lame',
      'favoring leg',
      'favoring paw',
      'holds leg up',
      'not bearing weight',
      'hops on three legs',
    ],
    protocol: 'Max Movement Pro – Joint Support',
    priority: 50,
  },
  {
    id: 'joint_stiffness',
    canonical: 'stiffness / joint pain',
    aliases: [
      'stiff',
      'stiffness',
      'stiff joints',
      'joint pain',
      'painful joints',
      'sore joints',
      'sore legs',
      'arthritis',
      'arthritic',
      'joint',
      'joints',
      'hip dysplasia',
      'elbow dysplasia',
      'slow to rise',
      'slow to stand',
      'hard to stand up',
      'trouble standing',
    ],
    protocol: 'Max Movement Pro – Joint Support',
    priority: 51,
  },
  {
    id: 'joint_mobility',
    canonical: 'reduced mobility',
    aliases: [
      'mobility',
      'cant walk',
      "can't walk",
      'trouble walking',
      'trouble stairs',
      'cant climb stairs',
      "can't climb stairs",
      'hesitates on stairs',
      'painful',
      'pain when moving',
      'yelps when moving',
      'gait',
      'asymmetric gait',
    ],
    protocol: 'Max Movement Pro – Joint Support',
    priority: 52,
  },

  // ── Spine (overlaps movement; separate protocol) ──────────────────────────
  {
    id: 'spine_back',
    canonical: 'back / spine pain',
    aliases: [
      'back pain',
      'sore back',
      'spine',
      'spinal',
      'slipped disc',
      'herniated disc',
      'ivdd',
      'hunched back',
      'arched back',
      'neck pain',
      'cant turn head',
      "can't turn head",
    ],
    protocol: 'Red Light Spine & Joint Support',
    priority: 55,
  },

  // ── Heart / cardio ────────────────────────────────────────────────────────
  {
    id: 'heart_stamina',
    canonical: 'exercise intolerance / fatigue',
    aliases: [
      'fatigue',
      'tired',
      'tired all the time',
      'low stamina',
      'gets tired quickly',
      'exercise intolerance',
      'cant keep up',
      "can't keep up",
      'collapsing on walks',
      'weakness',
      'lethargic',
      'lethargy',
      'low energy',
      'no energy',
      'sluggish',
    ],
    protocol: 'Heart Strong Cardio-Support',
    priority: 60,
  },
  {
    id: 'heart_respiratory',
    canonical: 'breathing / heart symptoms',
    aliases: [
      'breath',
      'breathing hard',
      'heavy breathing',
      'labored breathing',
      'short of breath',
      'panting excessively',
      'cough',
      'coughing',
      'heart',
      'cardiac',
      'heart murmur',
    ],
    protocol: 'Heart Strong Cardio-Support',
    priority: 61,
  },

  // ── Anxiety / behavior ────────────────────────────────────────────────────
  {
    id: 'calm_anxiety',
    canonical: 'anxiety / fear',
    aliases: [
      'anxious',
      'anxiety',
      'nervous',
      'fearful',
      'scared',
      'afraid',
      'stress',
      'stressed',
      'separation anxiety',
      'separation',
      'thunder',
      'fireworks',
      'noise phobia',
      'phobia',
      'panic',
      'panicking',
    ],
    protocol: 'Freedom Calm – Anxiety Relief',
    priority: 70,
  },
  {
    id: 'calm_behavior',
    canonical: 'restlessness / hyperactivity',
    aliases: [
      'restless',
      'restlessness',
      'cant settle',
      "can't settle",
      'hyper',
      'hyperactive',
      'overstimulated',
      'whining',
      'crying',
      'barking excessively',
      'destructive',
      'chewing furniture',
    ],
    protocol: 'Freedom Calm – Anxiety Relief',
    priority: 71,
  },

  // ── Liver / kidney / detox ────────────────────────────────────────────────
  {
    id: 'detox_liver_kidney',
    canonical: 'liver / kidney support',
    aliases: [
      'liver',
      'kidney',
      'kidneys',
      'renal',
      'detox',
      'toxin',
      'toxins',
      'jaundice',
      'yellow gums',
      'elevated liver enzymes',
      'kidney disease',
      'liver disease',
      'drinking lots of water',
      'excessive thirst',
      'urinating a lot',
      'frequent urination',
    ],
    protocol: 'Foundation Liver & Kidney Detox',
    priority: 80,
  },

  // ── Immune / systemic / senior cognitive (→ Immune #1 + Freedom Calm #2) ─
  {
    id: 'cognitive_senior',
    canonical: 'cognitive decline / senior support',
    aliases: [
      'senior dog',
      'senior',
      'elderly',
      'old dog',
      'getting old',
      'dementia',
      'cognitive dysfunction',
      'cds',
      'canine cognitive dysfunction',
      'disoriented',
      'disorientation',
      'confused',
      'confusion',
      'circling',
      'head tilt',
      'pacing',
      'pacing at night',
      'night pacing',
      'sundowning',
      'sundown',
      'staring at wall',
      'lost in house',
      'forgetful',
      'senile',
    ],
    protocol: 'Patriot Defender – Immunity & Vitality',
    priority: 88,
    forcedSecondary: 'Freedom Calm – Anxiety Relief',
  },
  {
    id: 'immune_infection',
    canonical: 'infection / immune weakness',
    aliases: [
      'infection',
      'infected',
      'immune',
      'immunity',
      'frequent illness',
      'always sick',
      'recurrent infection',
      'low immunity',
      'post surgery',
      'recovering',
      'wound not healing',
      'fever',
      'hot to touch',
    ],
    protocol: 'Patriot Defender – Immunity & Vitality',
    priority: 90,
  },
  {
    id: 'immune_appetite',
    canonical: 'appetite loss / general decline',
    aliases: [
      'wont eat',
      "won't eat",
      'not eating',
      'loss of appetite',
      'no appetite',
      'picky eater',
      'weight loss',
      'losing weight',
      'thin',
      'underweight',
      'vitality',
      'declining',
      'not himself',
      'not herself',
      'under the weather',
    ],
    protocol: 'Patriot Defender – Immunity & Vitality',
    priority: 91,
  },

  ...SPEC_CATEGORY_SYMPTOM_EXPANSIONS,
];

/* MERGED_ALIASES:START — generated by npm run symptom:merge — do not edit manually */
export const MERGED_SYMPTOM_ENTRIES: SymptomEntry[] = [];
/* MERGED_ALIASES:END */

export const FALLBACK_PROTOCOL = 'General Wellness Restore';
