/**
 * ViT spec-category lexicon expansions — natural owner phrases per protocol.
 * Merged into SYMPTOM_LEXICON; grouped by executive spec category for review.
 */
import type { SymptomEntry } from './symptom-entry';

const CLEAR_VISION = 'Clear Vision Defender – Eye Health Protocol';
const DENTAL = 'Fresh Smile Dental & Oral Health';
const ALLERGY = 'Allergy Shield – Skin & Coat Glow';
const GUT = "Buddy's Gut Balance & Cleanse";
const MAX_MOVEMENT = 'Max Movement Pro – Joint Support';
const SPINE = 'Red Light Spine & Joint Support';
const HEART = 'Heart Strong Cardio-Support';
const LIVER_KIDNEY = 'Foundation Liver & Kidney Detox';
const CALM = 'Freedom Calm – Anxiety Relief';
const IMMUNE = 'Patriot Defender – Immunity & Vitality';

export const SPEC_CATEGORY_SYMPTOM_EXPANSIONS: SymptomEntry[] = [
  // ── Spec 7: Eye & Vision Health Protocol ───────────────────────────────────
  {
    id: 'eye_dry_glaucoma',
    canonical: 'dry eye / glaucoma / pressure',
    aliases: [
      'dry eye',
      'dry eyes',
      'no tears',
      'cherry eye',
      'third eyelid',
      'prolapsed nictitans',
      'glaucoma',
      'eye pressure',
      'high eye pressure',
      'bulging eye',
      'eye bulging',
      'entropion',
      'ectropion',
      'rolled eyelid',
    ],
    protocol: CLEAR_VISION,
    priority: 13,
  },
  {
    id: 'eye_ulcer_injury',
    canonical: 'eye injury / ulcer',
    aliases: [
      'corneal ulcer',
      'eye ulcer',
      'ulcer on eye',
      'scratched eye',
      'eye scratch',
      'eye injury',
      'hurt eye',
      'one eye closed',
      'keeps eye closed',
      'eye swollen shut',
      'pink eye',
      'conjunctivitis',
      'eye infection',
    ],
    protocol: CLEAR_VISION,
    priority: 14,
  },

  // ── Spec 10 / Baseline: Holistic Wellness — Dental & Oral ───────────────────
  {
    id: 'dental_advanced',
    canonical: 'advanced dental / gum disease',
    aliases: [
      'periodontal',
      'periodontitis',
      'gum disease',
      'tooth decay',
      'rotten teeth',
      'missing teeth',
      'tooth extraction',
      'needs dental cleaning',
      'dental cleaning',
      'professional dental',
      'oral infection',
      'mouth infection',
      'tooth abscess',
      'facial swelling dental',
      'pawing at mouth',
      'rubbing face',
      'difficulty chewing',
      'only eats soft food',
    ],
    protocol: DENTAL,
    priority: 21,
  },

  // ── Spec 3 & 8: Skin / Allergy & Respiratory Relief ─────────────────────────
  {
    id: 'allergy_respiratory',
    canonical: 'respiratory allergy / sneezing',
    aliases: [
      'sneezing',
      'sneeze',
      'reverse sneeze',
      'reverse sneezing',
      'honking sneeze',
      'runny nose',
      'nasal discharge',
      'stuffy nose',
      'congested',
      'congestion',
      'wheezing',
      'wheeze',
      'asthma',
      'bronchitis',
      'pollen allergy',
      'seasonal allergies',
      'environmental allergy',
      'hay fever',
      'itchy nose',
      'rubbing nose',
    ],
    protocol: ALLERGY,
    priority: 28,
  },
  {
    id: 'allergy_ears_paws',
    canonical: 'allergic ears / paws / yeast',
    aliases: [
      'yeast infection',
      'yeasty smell',
      'yeast on skin',
      'ear infection',
      'ear infections',
      'chronic ear infections',
      'recurrent ear infections',
      'smelly ears',
      'head shaking',
      'shaking head',
      'itchy ears',
      'red ears',
      'brown ear discharge',
      'ear gunk',
      'interdigital cyst',
      'red paws',
      'brown paws',
      'licking between toes',
      'chewing nails',
      'foot licking',
    ],
    protocol: ALLERGY,
    priority: 29,
  },
  {
    id: 'skin_infection_coat',
    canonical: 'skin infection / coat quality',
    aliases: [
      'skin infection',
      'bacterial skin',
      'pyoderma',
      'mange',
      'demodex',
      'sarcoptic',
      'scabs',
      'crusty skin',
      'bumps on skin',
      'lumps on skin',
      'skin bumps',
      'oily coat',
      'greasy coat',
      'smelly skin',
      'skin odor',
      'skin smell',
      'flea allergy',
      'flea bites',
      'bug bites',
      'hives after walk',
      'reaction to food',
      'food allergy',
      'food sensitivity',
    ],
    protocol: ALLERGY,
    priority: 33,
  },

  // ── Spec 4: Digestive Harmony Protocol ─────────────────────────────────────
  {
    id: 'gut_stool_quality',
    canonical: 'abnormal stool / blood / mucus',
    aliases: [
      'blood in stool',
      'bloody stool',
      'bloody poop',
      'mucus in stool',
      'mucus in poop',
      'mucus stool',
      'black stool',
      'tar stool',
      'tarry stool',
      'greasy stool',
      'oily stool',
      'foul smelling poop',
      'smelly poop',
      'change in stool',
      'abnormal poop',
    ],
    protocol: GUT,
    priority: 38,
  },
  {
    id: 'gut_appetite_gi',
    canonical: 'appetite / GI discomfort',
    aliases: [
      'picky eater',
      'picky eating',
      "won't eat meals",
      'not finishing food',
      'eating less',
      'decreased appetite',
      'always hungry but skinny',
      'acid reflux',
      'reflux',
      'heartburn',
      'indigestion',
      'sour stomach',
      'pancreatitis',
      'gi upset',
      'gi issues',
      'stomach gurgling',
      'loud stomach',
      'eating grass',
      'eats grass',
      'scooting',
      'scoots',
      'anal gland issues',
      'full anal glands',
    ],
    protocol: GUT,
    priority: 39,
  },

  // ── Spec 2 & 9: Joint & Mobility / Musculoskeletal Recovery ────────────────
  {
    id: 'joint_advanced',
    canonical: 'advanced joint / orthopedic signs',
    aliases: [
      'wont jump on couch',
      "won't jump on couch",
      'wont jump on bed',
      "won't jump on bed",
      'cant jump',
      "can't jump",
      'slow on walks',
      'slowing down on walks',
      'yelps on stairs',
      'yelps going up stairs',
      'yelps when touched',
      'swollen joint',
      'swollen leg',
      'joint swelling',
      'degenerative joint disease',
      'djd',
      'osteoarthritis',
      'cruciate tear',
      'torn acl',
      'acl tear',
      'luxating patella',
      'slipping kneecap',
      'muscle wasting',
      'muscle loss',
      'leg weakness',
      'weak hind legs',
      'dragging back legs',
      'bunny hopping',
      'bunny hop gait',
    ],
    protocol: MAX_MOVEMENT,
    priority: 48,
  },
  {
    id: 'musculoskeletal_overlap',
    canonical: 'combined spine and joint issues',
    aliases: [
      'back and hip pain',
      'spine and joint pain',
      'back and leg pain',
      'neck and back pain',
      'stiff back and legs',
      'cant move back end',
      "can't move back end",
      'paralyzed back legs',
      'weak back legs',
      'wobbly back end',
      'hind end weakness',
    ],
    protocol: MAX_MOVEMENT,
    priority: 53,
    forcedSecondary: SPINE,
  },
  {
    id: 'recovery_rehab',
    canonical: 'injury recovery / rehab',
    aliases: [
      'recovering from injury',
      'recovery from surgery',
      'post surgery recovery',
      'after surgery',
      'rehab',
      'physical therapy',
      'soft tissue injury',
      'muscle strain',
      'pulled muscle',
      'sprain',
      'strained ligament',
      'tendon injury',
      'torn ligament',
      'orthopedic recovery',
      'limited mobility after injury',
      'crate rest recovery',
    ],
    protocol: SPINE,
    priority: 54,
    forcedSecondary: MAX_MOVEMENT,
  },

  // ── Spec 5: Heart & Vital Organs — Cardio ──────────────────────────────────
  {
    id: 'heart_advanced',
    canonical: 'advanced heart / circulation signs',
    aliases: [
      'heart failure',
      'chf',
      'congestive heart failure',
      'enlarged heart',
      'heart disease',
      'fainting',
      'fainted',
      'syncope',
      'collapsed during walk',
      'collapse episode',
      'blue gums',
      'pale gums',
      'cyanosis',
      'fluid in lungs',
      'pulmonary edema',
      'distended abdomen heart',
      'pot belly heart',
      'irregular heartbeat',
      'arrhythmia',
      'fast heartbeat',
      'rapid breathing at rest',
    ],
    protocol: HEART,
    priority: 58,
  },
  {
    id: 'heart_kidney_overlap',
    canonical: 'heart and kidney / fluid balance decline',
    aliases: [
      'heart and kidney disease',
      'cardiac and renal',
      'heart and kidney',
      'drinking a lot and coughing',
      'coughing and drinking more',
      'fluid retention',
      'swollen belly and weak',
      'edema and lethargy',
      'panting and weak',
    ],
    protocol: HEART,
    priority: 59,
    forcedSecondary: LIVER_KIDNEY,
  },

  // ── Spec 5: Heart & Vital Organs — Liver / Kidney / Detox ──────────────────
  {
    id: 'detox_advanced',
    canonical: 'advanced liver / kidney signs',
    aliases: [
      'kidney failure',
      'renal failure',
      'ckd',
      'chronic kidney disease',
      'stage 3 kidney',
      'stage 4 kidney',
      'elevated bun',
      'elevated creatinine',
      'protein in urine',
      'proteinuria',
      'blood in urine',
      'bloody urine',
      'straining to urinate',
      'difficulty urinating',
      'accidents in house urine',
      'incontinence',
      'leaking urine',
      'liver failure',
      'hepatic',
      'hepatitis',
      'cushing disease',
      'cushings',
      'addisons disease',
      'addison disease',
      'endocrine disease',
      'metabolic disease',
    ],
    protocol: LIVER_KIDNEY,
    priority: 78,
  },

  // ── Spec 6 / Calm: Cognitive overlap #2 & standalone behavior ────────────────
  {
    id: 'calm_triggers',
    canonical: 'situational anxiety triggers',
    aliases: [
      'vet anxiety',
      'vet fear',
      'afraid of vet',
      'car anxiety',
      'car sickness anxiety',
      'afraid of car',
      'travel anxiety',
      'grooming anxiety',
      'afraid of grooming',
      'storm anxiety',
      'storm fear',
      'reactive dog',
      'reactivity',
      'resource guarding',
      'aggressive when scared',
      'fear aggression',
      'startles easily',
      'on edge',
      'cannot relax',
      "won't calm down",
      'pacing from anxiety',
      'anxious pacing',
    ],
    protocol: CALM,
    priority: 69,
  },

  // ── Spec 1: Immune Vitality Protocol ───────────────────────────────────────
  {
    id: 'immune_advanced',
    canonical: 'immune support / recurrent illness',
    aliases: [
      'weak immune system',
      'run down',
      'always getting sick',
      'recurrent infections',
      'chronic infections',
      'slow to heal',
      'poor wound healing',
      'post chemo support',
      'cancer support',
      'on chemotherapy',
      'lymph nodes swollen',
      'swollen lymph nodes',
      'swollen glands',
      'autoimmune',
      'immune support',
      'boost immune system',
      'boost immunity',
      'antibiotic recovery',
      'after antibiotics',
      'post illness recovery',
    ],
    protocol: IMMUNE,
    priority: 87,
  },
  {
    id: 'wellness_baseline',
    canonical: 'holistic wellness / preventive baseline',
    aliases: [
      'wellness check',
      'wellness support',
      'preventive care',
      'preventative care',
      'overall health',
      'general health',
      'holistic support',
      'holistic wellness',
      'maintain health',
      'healthy aging support',
      'daily supplement',
      'nutritional support',
      'immune boost preventive',
      'routine wellness',
      'baseline wellness',
      'just want support',
      'proactive health',
    ],
    protocol: IMMUNE,
    priority: 92,
  },
];
